ALTER TABLE specializations ADD COLUMN created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE users ADD COLUMN created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE doctors ADD COLUMN created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE availability ADD COLUMN created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE appointments ADD COLUMN created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE admins ADD COLUMN created_at TIMESTAMP DEFAULT NOW();

